<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>GlassToKey.PrintStudio.Desktop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GlassToKey.PrintStudio.App/GlassToKey.PrintStudio.App.csproj" />
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>
</Project>
