<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GlassToKey.PrintStudio.Rendering</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GlassToKey.PrintStudio.Core/GlassToKey.PrintStudio.Core.csproj" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="Svg.Skia" />
  </ItemGroup>
</Project>
