<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GlassToKey.PrintStudio.App</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GlassToKey.PrintStudio.Core/GlassToKey.PrintStudio.Core.csproj" />
    <ProjectReference Include="../GlassToKey.PrintStudio.Rendering/GlassToKey.PrintStudio.Rendering.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
</Project>
